<?php/** @var \Magento\Newsletter\Block\Subscribe $block */?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <p class="subscribe-title"><?= $block->escapeHtml(__('Subscribe now to get special promo!')) ?></p>
        <form class="form subscribe"
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post">
            <div class="field newsletter">
                <label class="label" for="newsletter">
                    <span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           type="email"
                           id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                    />
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
